version = 1

[[analyzers]]
name = "python"
enabled = true

  [analyzers.meta]
  runtime_version = "3.12.x"
  type_checker = "mypy"
  max_line_length = 100

test_patterns = [
  "tests/**",
]

#[[transformers]]
#name = "ruff"
#enabled = true
