version = 1

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.12.x"
  type_checker = "mypy"
  max_line_length = 100

[[analyzers]]
name = "shell"

test_patterns = [
  "tests/**",
]
