version = 1

test_patterns = [
  "tests/**",
]

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.12.x"
  type_checker = "mypy"
  max_line_length = 100

[[transformers]]
name = "ruff"
enabled = true
